import { Header } from '../components/Header'
export default function PrivacyPage() {
  return <><Header connected={false} enabledCount={0} simpleMode /><main id="main-content" className="cd-shell">
    <section className="cd-hero"><p className="cd-eyebrow">PRIVACY INFORMATION</p><h1>Your video stays on your device.</h1><p>Current technical behavior of the ClearDrop prototype. This is not a completed store privacy policy.</p></section>
    <section className="cleardrop-controls space-y-4"><h2 className="text-xl font-semibold">What this version uses</h2><p>Phone camera frames and doorway comparison run in your browser. No microphone is requested. Your selected doorway area can be saved in this browser. Closing or hiding the app stops phone monitoring.</p><p>Ring preview tokens are sent to this app’s server and Ring to authorize camera access. The server stores them temporarily in memory, not the source repository. Ring delivers video through its streaming service. Browser sessions can end when the server restarts.</p><p>When email accounts are activated, Supabase processes your email, password authentication, verification emails and authentication logs. Passwords are managed by Supabase, not a custom ClearDrop password database. Hosting and authentication providers may retain operational access logs.</p><p>The illustrated demo and controlled camera tests use generated scenes. They contain no actual homeowner footage. Optional recognition models are downloaded from their model host; frames are analyzed locally.</p><h2 className="text-xl font-semibold">Your controls</h2><p>You can stop the camera, disconnect Ring, clear recent activity, and remove saved doorway settings by clearing this site’s browser data. Account settings include sign-out, password recovery and account deletion when configured. Deletion removes the authentication account and this browser’s doorway settings. Settings on another device must be cleared there; provider operational logs follow that provider’s retention policy.</p><h2 className="text-xl font-semibold">Before public release</h2><p>The operator must supply its legal identity, privacy/support contact, retention periods, hosting region, applicable rights process and a working public deletion URL. These have not been configured. Store distribution, approved consumer Ring linking and a security review are still pending.</p></section>
    <section className="cleardrop-controls mt-5"><h2 className="text-xl font-semibold">Optional review history and alerts</h2><p>If you enable private account sync in Ring’s More options, Supabase stores review identifiers, source category, status, version, notification-attempt outcome and timestamps. No video, frames, device IDs or Ring tokens are stored in that table. Rows are restricted to their account owner. Public demonstrations and unsynced sessions stay local.</p><p>Saved metadata remains until you delete closed reviews in Account settings or delete your account. There is a 200-review cap per account; automatic expiration is not implemented. Provider backups and operational logs follow provider retention rules. Notification requests are optional desktop alerts while the page is open, not background monitoring, caregiver alerts or proof of delivery.</p></section>
    <p className="cd-help mt-5"><a className="cd-text-link" href="/account">Account settings and deletion</a> · <a className="cd-text-link" href="/demo">Try the demo</a></p>
  </main></>
}
